spring:
  datasource:
    username: batch
    password: mysecretbatchpassword
    jdbcUrl: 'jdbc:mysql://localhost:3306/db_batch'
    driverClassName: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: 'false'
    jdbc:
      initialize-schema: always
consumer:
  datasource:
    username: consumer
    password: mysecretconsumerpassword
    jdbcUrl: 'jdbc:mysql://localhost:3307/db_app'
    driverClassName: com.mysql.cj.jdbc.Driver