version: '3.8'
services:
  system_db:
    image: mysql:latest
    container_name: mysql-batch
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretrootpassword
      - MYSQL_USER=batch
      - MYSQL_PASSWORD=mysecretbatchpassword
    ports:
      - '3306:3306'
    volumes:
      - system_db_data:/var/lib/mysql
  app_db:
    image: mysql:latest
    container_name: mysql-app
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretrootpassword
      - MYSQL_USER=consumer
      - MYSQL_PASSWORD=mysecretconsumerpassword
    ports:
      - '3307:3306'
    volumes:
      - app_db_data:/var/lib/mysql
volumes:
  system_db_data:
  app_db_data:
